# Use this file if you choose to publish on GPR

# You will also need to set a publishConfig in package.json
# Use your username for USER_NAME
#
# "publishConfig": {
#   "registry": "https://npm.pkg.github.com/USER_NAME"
# },

name: Publish on the Github Package Repository

# Publish only on release
# To publish on push, use:
# on:
#   push:
#      branches:
#        - 'main'
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This adds authentication for the Github registry
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: https://npm.pkg.github.com/
          scope: '@{USER_NAME}'

      - run: npm install
      - run: npm run test
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
